<?php

declare(strict_types=1);

namespace EzPhp\Auth\Console;

use EzPhp\Console\CommandInterface;

/**
 * Class AuthScaffoldCommand
 *
 * Console command: auth:scaffold
 *
 * Writes an example login/register controller and a matching routes file
 * into the application, wiring `Auth::login()`/`hashPassword()`/
 * `verifyPassword()` into a runnable (if minimal) flow. Not a full
 * user-management system — the two TODOs in the generated controller mark
 * exactly where the application must plug in its own user lookup/creation,
 * since `ez-php/auth` has no user model or schema of its own.
 *
 * Usage:
 *   ez auth:scaffold
 *
 * Refuses to overwrite an existing app/Controllers/AuthController.php.
 *
 * @package EzPhp\Auth\Console
 */
final readonly class AuthScaffoldCommand implements CommandInterface
{
    /**
     * AuthScaffoldCommand Constructor
     *
     * @param string|null $basePath Application root (contains app/, routes/). Null (the
     *                              default, used when registered by class name via
     *                              `registerCommand()`) resolves to the working directory at
     *                              run time — `php ez` runs from the project root.
     */
    public function __construct(private ?string $basePath = null)
    {
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return 'auth:scaffold';
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return 'Write an example login/register controller and routes file';
    }

    /**
     * @return string
     */
    public function getHelp(): string
    {
        return "Usage: ez auth:scaffold\n\n"
            . "Writes app/Controllers/AuthController.php and routes/auth.php with an\n"
            . "example login/register flow built on the Auth facade. Require the routes\n"
            . "file from routes/web.php to activate it:\n"
            . "  require __DIR__ . '/auth.php';\n\n"
            . 'Refuses to run if AuthController.php already exists.';
    }

    /**
     * @param list<string> $args
     *
     * @return int
     */
    public function handle(array $args): int
    {
        $basePath = $this->basePath ?? (getcwd() ?: '.');
        $controllerPath = $basePath . '/app/Controllers/AuthController.php';
        $routesPath = $basePath . '/routes/auth.php';

        if (file_exists($controllerPath)) {
            fwrite(STDERR, "AuthController already exists: app/Controllers/AuthController.php\n");

            return 1;
        }

        $controllerDir = dirname($controllerPath);

        if (!is_dir($controllerDir) && !mkdir($controllerDir, 0o755, true) && !is_dir($controllerDir)) {
            fwrite(STDERR, "Could not create directory: $controllerDir\n");

            return 1;
        }

        $routesDir = dirname($routesPath);

        if (!is_dir($routesDir) && !mkdir($routesDir, 0o755, true) && !is_dir($routesDir)) {
            fwrite(STDERR, "Could not create directory: $routesDir\n");

            return 1;
        }

        if (file_put_contents($controllerPath, $this->controllerStub()) === false) {
            fwrite(STDERR, "Failed to write: app/Controllers/AuthController.php\n");

            return 1;
        }

        if (file_put_contents($routesPath, $this->routesStub()) === false) {
            fwrite(STDERR, "Failed to write: routes/auth.php\n");

            return 1;
        }

        echo "Created: app/Controllers/AuthController.php\n";
        echo "Created: routes/auth.php\n";
        echo "Require it from routes/web.php to activate: require __DIR__ . '/auth.php';\n";

        return 0;
    }

    /**
     * @return string
     */
    private function controllerStub(): string
    {
        return <<<'PHP'
            <?php

            declare(strict_types=1);

            namespace App\Controllers;

            use EzPhp\Auth\Auth;
            use EzPhp\Http\Request;
            use EzPhp\Http\Response;

            /**
             * Example login/register flow generated by `ez auth:scaffold`.
             *
             * This is a starting point, not a complete user-management system —
             * ez-php/auth has no user model or schema of its own. Replace the two
             * TODOs below with your application's actual user lookup/creation.
             */
            final class AuthController
            {
                public function login(Request $request): Response
                {
                    $email = (string) ($request->input('email') ?? '');
                    $password = (string) ($request->input('password') ?? '');

                    // TODO: replace with your own user lookup by email, e.g. via a
                    // UserRepository or UserProviderInterface-backed service. It must
                    // return an object implementing EzPhp\Auth\UserInterface, or null.
                    $user = $this->findUserByEmail($email);

                    if ($user === null || !Auth::verifyPassword($password, $user->passwordHash)) {
                        return new Response('Invalid credentials', 401);
                    }

                    Auth::login($user);

                    return new Response('Logged in');
                }

                public function register(Request $request): Response
                {
                    $email = (string) ($request->input('email') ?? '');
                    $password = (string) ($request->input('password') ?? '');
                    $hash = Auth::hashPassword($password);

                    // TODO: replace with your own user creation, persisting $email
                    // and $hash, then return the newly created user record. It must
                    // implement EzPhp\Auth\UserInterface.
                    $user = $this->createUser($email, $hash);

                    Auth::login($user);

                    return new Response('Registered', 201);
                }

                private function findUserByEmail(string $email): ?object
                {
                    throw new \RuntimeException(
                        __METHOD__ . '() is a scaffold stub — implement your own user lookup.',
                    );
                }

                private function createUser(string $email, string $passwordHash): object
                {
                    throw new \RuntimeException(
                        __METHOD__ . '() is a scaffold stub — implement your own user creation.',
                    );
                }

                public function logout(Request $request): Response
                {
                    Auth::logout();

                    return new Response('Logged out');
                }
            }
            PHP;
    }

    /**
     * @return string
     */
    private function routesStub(): string
    {
        return <<<'PHP'
            <?php

            declare(strict_types=1);

            use App\Controllers\AuthController;
            use EzPhp\Routing\Router;

            /** @var Router $router */
            $router->post('/login', [AuthController::class, 'login']);
            $router->post('/register', [AuthController::class, 'register']);
            $router->post('/logout', [AuthController::class, 'logout']);
            PHP;
    }
}
